version = 1

exclude_patterns = ["*/functions/lib/*.js"]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  environment = ["nodejs"]
  dialect = "typescript"
  dependency_file_paths = [
    "package.json",
    "abandoned-cart-emails/functions/package.json",
    "send-message/functions/package.json",
    "sendgrid-marketing-campaigns-sync/functions/package.json"
  ]
